---
title: "data cleaning and preparation"
output: html_document
date: "`r Sys.Date()`"
---

```{r packages, include=FALSE}
library(tidyverse)
library(data.table)
library(googlesheets4)
library(forcats)
library(RCurl)
library(httr)
library(jsonlite)
library(lubridate)
library(zoo)
library(roll)
library(TTR)
library(janitor)
library(broom)
library(hms)
library(wrapr)
```

```{r load data}
# Function to read data from Google Sheets
read_sheet_clean <- function(url, sheet_name) {
  read_sheet(url, sheet = sheet_name) |>
    clean_names()
}

# Load the token
token_path <- "~/Desktop/Ltips/etude_ai.rds"
token <- readRDS(token_path)

# Use the token for authentication
gs4_auth(token = token)

# Google Sheets URLs
ss_url <- "https://docs.google.com/spreadsheets/d/1pBGkvxKph4C9PsQtpgaD9_zcOlOgbQESwXcp3y-t0eU/edit?resourcekey#gid=685045347"
hist_url <- "https://docs.google.com/spreadsheets/d/1_mOA10uAX-iDvykUbLbiQMaxl4uvUncgbFPcJYZA57o/edit?resourcekey#gid=2007602671"

# Read data from Google Sheets and clean
hist <- read_sheet_clean(hist_url, "Réponses au formulaire 1") |>
  select(-32) |>
  filter(recrute == "oui") |>
  mutate(across(where(is.list), ~ unlist(.)),
         date_de_naissance = ymd(date_de_naissance),
         age = as.numeric(difftime(Sys.Date(), date_de_naissance, units = "days")) / 365.25)

info <- read_sheet_clean(ss_url, "info") |>
  select(-c(virement, lien_forms:max_number_6)) |>
  unite(nom, prenom, nom, sep = " ", remove = TRUE) |>
  mutate(ath_id = unlist(ath_id)) 

srss <- read_sheet_clean(ss_url, "srss") |>
  rename("courriel" = "adresse_courriel")

# load data intervals
athletes_power <- vector("list")
for (i in 1:nrow(info)) {
  username <- "API_KEY"
  key <- paste0(info$api_key[i])
  athlete_id <- paste0(info$ath_id[i])
  params = list(
    # sélection PPR standard et post 2k et 3k kj pour dernier 42j, saison, dernière saison et records tout temps
    curves = "
    s0,s0-kj0,s0-kj1,
    s1,s1-kj0,s1-kj1,
    all,all-kj0,all-kj1
    ",
    # filters = '[{"field_id":"type","value":["Ride","VirtualRide"]}]',
    type = "Ride",
    # ajuster date pour select 42 jours en fonction de date today Sys.Date()
    from = paste0(Sys.Date(), "T14:40:36")
  )
  url_act <-
    sprintf("https://intervals.icu/api/v1/athlete/%s/power-curves.csv",
            athlete_id)
  athletes_power[[athlete_id]] <-
    httr::GET(url_act, authenticate(username, key), query = params) |>
    content()
}

athletes_wellness <- vector("list")
for(i in 1:nrow(info)){
  username <- "API_KEY"
  key <- paste0(info$api_key[i])
  athlete_id <- paste0(info$ath_id[i])
  url_act <- sprintf("https://intervals.icu/api/v1/athlete/%s/wellness.csv", athlete_id)
  athletes_wellness[[athlete_id]] <- httr::GET(url_act, authenticate(username, key)) |>
  content()
}

athletes_activities <- vector("list")
for(i in 1:nrow(info)){
  username <- "API_KEY"
  key <- paste0(info$api_key[i])
  athlete_id <- paste0(info$ath_id[i])
  url_act <- sprintf("https://intervals.icu/api/v1/athlete/%s/activities.csv", athlete_id)
  athletes_activities[[athlete_id]] <- httr::GET(url_act, authenticate(username, key)) |>
    content()
}
```

## Cleaning and preparing data

```{r clean data intervals}
# Add the column 'ath_id' to each df in the list
athletes_power <-
  Map(cbind, athletes_power,
      ath_id = names(athletes_power))

athletes_wellness <-
  Map(cbind, athletes_wellness,
      ath_id = names(athletes_wellness))

athletes_activities <-
  Map(cbind, athletes_activities,
      ath_id = names(athletes_activities))

# Group the df in the list into a single df and merge it with the 'info' df
athletes_power_df <-
  rbindlist(athletes_power, fill=TRUE) |>
  janitor::clean_names()

athletes_power_clean <- left_join(athletes_power_df, info, by = "ath_id")

# add weight to df to calculate w/kg
weight_df <- hist |> 
  rename(courriel = adresse_de_courriel) |> 
  select(courriel, sexe, poids_kg)

athletes_power_clean <- left_join(athletes_power_clean, weight_df, by = "courriel") 

athletes_wellness_df <-
  rbindlist(athletes_wellness, fill = TRUE)

# correct +1 day for android hrv4trainning
athletes_wellness_clean <- athletes_wellness_df |>
  left_join(info, by = "ath_id") |>
  mutate(
    hrv = if_else(hrv_android_minus_1d == "oui", lead(hrv), hrv),
    restingHR = if_else(hrv_android_minus_1d == "oui", lead(restingHR), restingHR)
  ) |>
  select(date, ath_id, courriel:hrv_android_minus_1d, hrv, restingHR) |>
  left_join(
    athletes_wellness_df |>
      select(-hrv, -restingHR),
    by = c("date", "ath_id")
  ) |>
 arrange(date) 
  
athletes_activities_df <- rbindlist(athletes_activities)
athletes_activities_df <- left_join(athletes_activities_df, info, by = "ath_id")

# Define activity types for special data manipulation
activity_types <- c("Ride", "VirtualRide", "GravelRide", "MountainBikeRide")

# Define variables to sum, take max, and take average
vars_sum <- c(
  "moving_time", "distance", "elapsed_time", "total_elevation_gain",
  "calories", "icu_joules", "icu_training_load",
  "hr_z1_secs", "hr_z2_secs", "hr_z3_secs", "hr_z4_secs",
  "hr_z5_secs", "hr_z6_secs", "hr_z7_secs",
  "z1_secs", "z2_secs", "z3_secs", "z4_secs", "z5_secs",
  "z6_secs", "z7_secs"
)

vars_max <- c(
  "max_speed", "max_heartrate", "icu_eftp", "icu_pm_ftp",
  "icu_pm_cp", "icu_pm_w_prime", "icu_pm_p_max", "icu_hrrc",
  "icu_ftp", "icu_w_prime", "icu_weight"
)

vars_avg <- c(
  "average_speed", "average_heartrate", "average_cadence",
  "icu_average_watts", "icu_normalized_watts", "icu_intensity",
  "icu_variability", "icu_efficiency"
)

# Calculate metrics for selected activity types
bike_metrics_sum <- athletes_activities_df %>%
  filter(type %in% activity_types) %>%
  mutate(date = as.Date(start_date_local)) %>%
  group_by(date, ath_id) %>%
  summarise(across(vars_sum, ~ if(any(!is.na(.))) sum(., na.rm = TRUE) else NA, .names = "{.col}_bike"), .groups = "keep")

bike_metrics_max <- athletes_activities_df %>%
  filter(type %in% activity_types) %>%
  mutate(date = as.Date(start_date_local)) %>%
  group_by(date, ath_id) %>%
  summarise(across(vars_max, ~ if(any(!is.na(.))) max(., na.rm = TRUE) else NA, .names = "{.col}_bike"), .groups = "keep")

bike_metrics_avg <- athletes_activities_df %>%
  filter(type %in% activity_types) %>%
  mutate(date = as.Date(start_date_local)) %>%
  group_by(date, ath_id) %>%
  summarise(across(vars_avg, ~ if(any(!is.na(.))) mean(., na.rm = TRUE) else NA, .names = "{.col}_bike"), .groups = "keep")

# Calculate metrics only for non selected activity types
other_metrics_sum <- athletes_activities_df %>%
  filter(!type %in% activity_types) %>%
  mutate(date = as.Date(start_date_local)) %>%
  group_by(date, ath_id) %>%
  summarise(across(vars_sum, ~ if(any(!is.na(.))) sum(., na.rm = TRUE) else NA, .names = "{.col}_other"), .groups = "keep")

other_metrics_max <- athletes_activities_df %>%
  filter(!type %in% activity_types) %>%
  mutate(date = as.Date(start_date_local)) %>%
  group_by(date, ath_id) %>%
  summarise(across(vars_max, ~ if(any(!is.na(.))) max(., na.rm = TRUE) else NA, .names = "{.col}_other"), .groups = "keep")

other_metrics_avg <- athletes_activities_df %>%
  filter(!type %in% activity_types) %>%
  mutate(date = as.Date(start_date_local)) %>%
  group_by(date, ath_id) %>%
  summarise(across(vars_avg, ~ if(any(!is.na(.))) mean(., na.rm = TRUE) else NA, .names = "{.col}_other"), .groups = "keep")

result <-
  Reduce(
    function(x, y)
      merge(x, y, by = c("date", "ath_id"), all = TRUE),
    list(
      bike_metrics_sum,
      bike_metrics_max,
      bike_metrics_avg,
      other_metrics_sum,
      other_metrics_max,
      other_metrics_avg
    )
  )

athletes_activities_clean <- left_join(result, info, by = c("ath_id")) |>
  select(date,
         nom,
         courriel,
         ath_id,
         api_key,
         everything()) |> 
  # replace all occurrences of -Inf, NA, and NaN with 0
  mutate_at(vars(-1:-5), ~ ifelse(is.infinite(.x) | is.na(.x) | is.nan(.x), 0, .x))
```

```{r clean data srss}
# Merge the datasets
srss_clean <- merge(srss, info, by = "courriel") |>
  # Correct date for European subjects
  mutate(
    # Convert horodatage to DateTime with time zone
    horodatage = if_else(
      courriel %in% c("tam.kroll@gmail.com", "jerome@bicyclettelab.com"),
      with_tz(as_datetime(as.numeric(horodatage), origin = "1970-01-01"), tz = "Europe/Paris"),
      # Set time zone to "UTC" for non-selected rows
      force_tz(as_datetime(as.numeric(horodatage), origin = "1970-01-01"), tzone = "UTC")
    ),
    # Keep only the date part of horodatage to prevent conversion day for European subjects
    date = as.Date(substr(horodatage, 1, 10))
  ) |>
  ungroup() |>
  rename(
    missed_form_date = date_formulaire_manque_uniquement,
    sleep_quality = quelle_etait_la_qualite_de_votre_sommeil_la_nuit_derniere,
    bed_time = a_quelle_heure_vous_etes_vous_couche,
    wake_up_time = a_quelle_heure_vous_etes_vous_leve,
    training_phase = dans_quelle_phase_dentrainement_etes_vous_actuellement,
    competition = participez_vous_a_une_competition_aujourdhui,
    injured = etes_vous_blesse_presentement,
    sick = etes_vous_malade_aujourd_hui,
    comments = commentaires_precisions,
    training_yesterday = vous_etes_vous_entraine_hier,
    training_type_1 = type_dentrainement_number_1,
    feeling_training_1 = comment_evalueriez_vous_votre_ressenti_global_pendant_votre_seance_dentrainement_number_1_hier,
    rpe_training_1 = perception_deffort_rpe_moyenne_lors_de_votre_entrainement_number_1_hier,
    duration_training_1 = duree_totale_de_lentrainement_number_1_en_minutes_hier,
    training_type_2 = type_dentrainement_number_2,
    feeling_training_2 = comment_evalueriez_vous_votre_ressenti_global_pendant_votre_seance_dentrainement_number_2_hier,
    rpe_training_2 = perception_deffort_rpe_moyenne_lors_de_votre_entrainement_number_2_hier,
    duration_training_2 = duree_totale_de_lentrainement_number_2_en_minutes_hier,
    training_type_3 = type_dentrainement_number_3,
    feeling_training_3 = comment_evalueriez_vous_votre_ressenti_global_pendant_votre_seance_dentrainement_number_3_hier,
    rpe_training_3 = perception_deffort_rpe_moyenne_lors_de_votre_entrainement_number_3_hier,
    duration_training_3 = duree_totale_de_lentrainement_number_3_en_minutes_hier,
    training_type_4 = type_dentrainement_number_4,
    feeling_training_4 = comment_evalueriez_vous_votre_ressenti_global_pendant_votre_seance_dentrainement_number_4_hier,
    rpe_training_4 = perception_deffort_rpe_moyenne_lors_de_votre_entrainement_number_4_hier,
    duration_training_4 = duree_totale_de_lentrainement_number_4_en_minutes_hier
  ) |>
  # recode srss vars 0-6 to 1-7 to eliminate na if 0
  mutate_at(.vars = 4:11,
            .funs = list(~ recode(., !!!setNames(1:7, 0:6)))) |>
  # recode sleep_quality vars 0-10 to 1-11 to eliminate na if 0
  mutate_at(.vars = 12,
            .funs = list(~ recode(., !!!setNames(1:11, 0:10)))) |>
  # recode feel training vars -5 - +5 to 1-11
  mutate(across(c(22, 27, 32, 37), ~ parse_number(.))) |>
  mutate_at(
    vars(22, 27, 32, 37),
    # Select columns starting with "col"
    ~ case_when(
      . == -5 ~ 1,
      . == -4 ~ 2,
      . == -3 ~ 3,
      . == -2 ~ 4,
      . == -1 ~ 5,
      . == 0 ~ 6,
      . == 1 ~ 7,
      . == 2 ~ 8,
      . == 3 ~ 9,
      . == 4 ~ 10,
      . == 5 ~ 11,
      TRUE ~ .  # Keep other values unchanged
    )
  ) |>
  mutate(
    bed_time = as_hms(bed_time),
    wake_up_time = as_hms(wake_up_time),
    # Adjust bed_time to 24-hour format if it's between 6 am and 6 pm but not for Alain St-Louis
    bed_time =
      ifelse(
        bed_time >= 6 * 60 * 60 &
          bed_time <= 18 * 60 * 60 &
          courriel != "alainst_louis@hotmail.com",
      bed_time + 12 * 60 * 60,
      bed_time
    ),
    # Convert bed_time to hms format
    bed_time = as_hms(bed_time),
    
    # Adjust wake_up_time to 24-hour format if it's 18h instead of 6h

    
    # Calculate sleep_time based on bed_time and wake_up_time
    sleep_time = ifelse(
      bed_time <= wake_up_time,
      wake_up_time - bed_time,
      24 * 60 * 60 - bed_time + wake_up_time
    ),
    # Convert sleep_time from seconds to hours
    sleep_time = sleep_time / 60 / 60,
    # Apply a correction for potential errors or outliers
    sleep_time =
      ifelse(sleep_time < 0 | sleep_time > 15, 8, sleep_time),
    sleep_load = sleep_time * sleep_quality,
    injured = ifelse(injured == "NULL", NA, injured),
    comments = ifelse(comments == "NULL", NA, comments)
  ) |>
  select(
    date,
    horodatage,
    missed_form_date,
    nom,
    courriel,
    hrv_android_minus_1d,
    ath_id,
    api_key,
    4:19,
    21:24,
    26:29,
    31:34,
    36:39,
    45:46
  ) |>
  # if missed form change date based on missed_form_date
  mutate(missed_form_date = as.Date(missed_form_date)) |>
  mutate(date = ifelse(!is.na(missed_form_date), missed_form_date, date),
         date = as.Date(date)) |>
  # Adjust date for duplicate entries mercier time form 23:30 = date same day form morning
  group_by(nom, date) |>
  mutate(
    date = case_when(
      duplicated(date) ~ date - 1,  # Subtract one day if duplicate date
      TRUE ~ date  # Keep the original date otherwise
    )
  ) |>
  
  # correct if bet time is 12:00:00 tranform to 24:00:00 but need to be 00:00:00
  
  # order date for roll av
  arrange(date)
```

## Variables creation

```{r vars intervals power}
# estimation CP W' modele 1/temps
data_cp <- athletes_power_clean |>
  select(courriel, secs, this_season) |>
  rename(TTE = secs,
         PO = this_season) |>
  na.omit() |>
  # records saison entre 3min et 20min
  filter(TTE %in% c(180, 720)) |>
  mutate(temps_1 = 1 / TTE) |>
  group_by(courriel) |>
  # broom clean lm
  do(tidy(lm(PO ~ temps_1, .))) |>
  select(1:3) |>
  pivot_wider(names_from = term, values_from = estimate) |>
  setNames(c("courriel", "cp", "w")) |>
  mutate_at(vars(cp,
                 w),
            ~ round(.))

intervals_power <-
  left_join(athletes_power_clean, data_cp, by = c("courriel")) |> 
  mutate(cp_wkg = cp / poids_kg)

```

```{r vars intervals wellness}
intervals_wellness <- athletes_wellness_clean |>
  rename(rhr = restingHR) |>
  group_by(nom) |>
  mutate(across(
    c(hrv, rhr),
    list(
      ravg7 = ~ rollapply(
        .,
        7,
        mean,
        na.rm = TRUE,
        fill = NA,
        align = 'right',
        partial = TRUE
      ),
      ravg60 = ~ rollapply(
        .,
        60,
        mean,
        na.rm = TRUE,
        fill = NA,
        align = 'right',
        partial = TRUE
      ),
      rsd7 = ~ roll_sd(., 7, min_obs = 1),
      norm = ~ 0.75 * roll_sd(., 60, min_obs = 1)
          ),
    .names = "{.col}_{.fn}"
  )) |>
  mutate(hrv_cv_ravg7 = hrv_rsd7 / hrv_ravg7 * 100) |> 
  ungroup()
```

```{r vars intervals activities}
calculate_metrics <- function(data, prefix) {
  data %>%
    mutate(
      !!paste0("aigue_7_", prefix) := EMA(!!sym(prefix), n = 1, ratio = 2 / (1 + 7)),
      !!paste0("chronique_42_", prefix) := EMA(!!sym(prefix), n = 1, ratio = 2 / (1 + 42)),
      !!paste0("ACWR_", prefix) := !!sym(paste0("aigue_7_", prefix)) / !!sym(paste0("chronique_42_", prefix)),
      !!paste0("fraicheur_", prefix) := !!sym(paste0("chronique_42_", prefix)) - !!sym(paste0("aigue_7_", prefix)),
      !!paste0(prefix, "_7_mean") := rollapply(!!sym(prefix), 7, mean, na.rm = TRUE, fill = NA, align = 'right', partial = TRUE),
      !!paste0(prefix, "_7_sd") := roll_sd(!!sym(prefix), 7, min_obs = 1),
      !!paste0("monotonie_", prefix) := round(!!sym(paste0(prefix, "_7_mean")) / !!sym(paste0(prefix, "_7_sd")), digits = 1),
      !!paste0("monotonie_", prefix) := ifelse(!!sym(paste0("monotonie_", prefix)) >= 10, 0, !!sym(paste0("monotonie_", prefix)))
    )
}

# Apply the function for both load_rpe and load_rpe_velo
intervals_activities <- athletes_activities_clean %>%
  group_by(nom) %>%
  # filter df to get the first day the form was filed and limit computing time
  filter(date >= date("2024-01-17")) %>%
  ungroup() |>
  group_by(date, ath_id) %>%
  mutate(
    lutrimp_zone1_bike = hr_z1_secs_bike + hr_z2_secs_bike * 1,
    lutrimp_zone2_bike = hr_z3_secs_bike + hr_z4_secs_bike * 2,
    lutrimp_zone3_bike = hr_z5_secs_bike + hr_z6_secs_bike + hr_z7_secs_bike * 3,
    lutrimp_bike = lutrimp_zone1_bike + lutrimp_zone2_bike + lutrimp_zone3_bike,
    zone1_bike = z1_secs_bike + z2_secs_bike,
    zone2_bike = z3_secs_bike + z4_secs_bike,
    zone3_bike = z5_secs_bike + z6_secs_bike + z7_secs_bike,
    zone1_h_bike = zone1_bike / 3600,
    zone2_h_bike = zone2_bike / 3600,
    zone3_h_bike = zone3_bike / 3600,
    across(
      c(icu_joules_bike, lutrimp_bike, icu_training_load_bike),
      ~ replace_na(., 0)
    )
  ) %>%
  ungroup() %>%
  filter(n() > 1) %>% 
  group_by(ath_id) %>%
  calculate_metrics(., "icu_joules_bike") %>%
  calculate_metrics(., "lutrimp_bike") %>%
  calculate_metrics(., "icu_training_load_bike") %>%
  mutate_at(vars(icu_average_watts_bike, average_heartrate_bike),
            ~ replace(., . == 0, NA)) |> 
  mutate(
    # aerobic efficiency
    efficacite_aerobique_bike = icu_average_watts_bike / average_heartrate_bike,
    efficacite_aerobique_ravg7_bike = rollapply(
      efficacite_aerobique_bike,
      7,
      mean,
      na.rm = TRUE,
      fill = NA,
      align = 'right',
      partial = TRUE
    ),
    efficacite_aerobique_ravg60_bike = rollapply(
      efficacite_aerobique_bike,
      60,
      mean,
      na.rm = TRUE,
      fill = NA,
      align = 'right',
      partial = TRUE
    ),
    efficacite_aerobique_norm_bike = 0.75 * (roll_sd(efficacite_aerobique_bike, 60, min_obs = 1)),
    # conversions
    temps_h_bike = round(moving_time_bike / 3600, digits = 1),
    j_h_bike = icu_joules_bike / temps_h_bike,
    lutrimp_h_bike = lutrimp_bike / temps_h_bike
  ) |>
  ungroup() |>
  mutate(across(where(is.numeric), ~ ifelse(is.infinite(.x) |
                                              is.nan(.x), 0, .x)))
```

```{r vars srss wellness}
# Define the conversion function from z-score to t-score
z_to_t <- function(z) {
  return ((z * 10) + 50)
}

srss_wellness <- srss_clean |>
  # Remove training data to create a new df with the correct day (-1) for training data next
  select(-25:-40) |>
  group_by(nom) |>
  mutate(
    # Define rolling averages and other derived metrics
    across(
      c(
        physical_performance_capability,
        mental_performance_capability,
        emotional_balance,
        overall_recovery,
        muscular_stress,
        lack_of_activation,
        negative_emotional_state,
        overall_stress,
        sleep_quality,
        sleep_time,
        sleep_load
      ),
      list(
        ravg7 = ~ rollapply(
          .,
          7,
          mean,
          na.rm = TRUE,
          fill = NA,
          align = 'right',
          partial = TRUE
        ),
        ravg60 = ~ rollapply(
          .,
          60,
          mean,
          na.rm = TRUE,
          fill = NA,
          align = 'right',
          partial = TRUE
        ),
        norm = ~ 0.75 * (roll_sd(., 60, min_obs = 1))
      ),
      .names = "{.col}_{.fn}"
    ),
    # Define z-scores
    # normal
    across(
      c(
        physical_performance_capability,
        mental_performance_capability,
        emotional_balance,
        overall_recovery
      ),
      list(z = ~ roll_scale(.x, 7, min_obs = 1)),
      .names = "{.col}_z"
    ),
    # minus to make negative z score positive
    across(
      c(
        muscular_stress,
        lack_of_activation,
        negative_emotional_state,
        overall_stress
      ),
      list(z = ~ -roll_scale(.x, 7, min_obs = 1)),
      .names = "{.col}_z"
    ),
    # Define the conversion function from z-score to t-score
    across(ends_with("_z"), ~ z_to_t(.x), .names = "{.col}_t")
  ) |>
  ungroup() |>
  mutate(
    # Replace NA with 0 in z-score columns
    across(ends_with("z"), ~ replace(., is.na(.), 0)),
    # Calculate wellness score
    wellness = rowMeans(select(cur_data_all(), ends_with("_z")), na.rm = TRUE),
    wellness_t = rowMeans(select(cur_data_all(), ends_with("_t")), na.rm = TRUE),
    wellness_norm = 0.75 * (roll_sd(wellness, 60, min_obs = 1)),
    wellness_t_ravg7 = rollapply(
      wellness_t,
      7,
      mean,
      na.rm = TRUE,
      fill = NA,
      align = 'right',
      partial = TRUE
    ),
    wellness_t_ravg60 = rollapply(
      wellness_t,
      60,
      mean,
      na.rm = TRUE,
      fill = NA,
      align = 'right',
      partial = TRUE
    ),
    wellness_norm_t = 0.75 * (roll_sd(wellness_t, 60, min_obs = 1))
  ) |>
  ungroup() |>
  # Recode training phase
  mutate(
    training_phase = fct_recode(
      training_phase,
      "recovery" = "Faible volume / récupération",
      "overload" = "Volume / intensité",
    )
  )
```

```{r vars srss training}
# Pivot the dataframe to long format
srss_training_session <- srss_clean |>
  # keep only training data
  select(
    date,
    nom,
    starts_with("training_type"),
    starts_with("feeling_training"),
    starts_with("rpe_training"),
    starts_with("duration_training")
  ) |>
  pivot_longer(
    cols = -c(date, nom),
    names_to = c(".value", "set"),
    names_pattern = "(\\D+)(\\d+)"
  ) |>
  mutate(set = as.integer(set)) |>  # Convert 'set' column to integer if needed
  rename_at(vars(4:7), ~ sub("_$", "", .)) |>
  rename(day_training_number = set) |>
  filter(!is.na(training_type)) |> # remove lines with no training
  # Date - 1 to adjust date to align with the correct day
  mutate(date = date - 1) |>
  group_by(date, nom) |>
  mutate(
    session_load_rpe = rpe_training * duration_training
  ) |> 
  ungroup() 

# df containing aggregated data for each day and training_type
srss_training_day <- srss_training_session %>%
  group_by(date, nom, training_type) %>%
  summarise(
    feeling_training_mean = mean(feeling_training, na.rm = TRUE),
    rpe_training_mean = mean(rpe_training, na.rm = TRUE),
    duration_training_sum = sum(duration_training, na.rm = TRUE),
    load_rpe = sum(session_load_rpe, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  ungroup() %>%
  # keep only avg or sum of day vars
  select(date,
         nom,
         training_type,
         feeling_training_mean:load_rpe) %>%
  distinct() %>%
  pivot_wider(
    names_from = training_type,
    values_from = c(
      feeling_training_mean,
      rpe_training_mean,
      duration_training_sum,
      load_rpe
    ),
    names_sep = "_"
  ) %>%
  clean_names()

# Compute additional metrics
srss_training_day <- srss_training_day %>%
  mutate(
    feeling_training = rowMeans(select(
      srss_training_day,
      c(
        feeling_training_mean_velo,
        feeling_training_mean_musculation,
        feeling_training_mean_autre
      )
    ), na.rm = TRUE),
    rpe_training = rowMeans(select(
      srss_training_day,
      c(
        rpe_training_mean_velo,
        rpe_training_mean_musculation,
        rpe_training_mean_autre
      )
    ), na.rm = TRUE),
    duration_training = rowSums(select(
      srss_training_day,
      c(
        duration_training_sum_velo,
        duration_training_sum_musculation,
        duration_training_sum_autre
      )
    ), na.rm = TRUE),
    load_rpe = rowSums(select(
      srss_training_day,
      c(load_rpe_velo,
        load_rpe_musculation,
        load_rpe_autre)
    ), na.rm = TRUE)
  )
```

```{r srss wellness training}
# Define a function to calculate metrics for load_rpe and load_rpe_velo
calculate_metrics <- function(data, prefix) {
  data %>%
    mutate(
      !!paste0("aigue_7_", prefix) := EMA(!!sym(prefix), n = 1, ratio = 2 / (1 + 7)),
      !!paste0("chronique_42_", prefix) := EMA(!!sym(prefix), n = 1, ratio = 2 / (1 + 42)),
      !!paste0("ACWR_", prefix) := !!sym(paste0("aigue_7_", prefix)) / !!sym(paste0("chronique_42_", prefix)),
      !!paste0("fraicheur_", prefix) := !!sym(paste0("chronique_42_", prefix)) - !!sym(paste0("aigue_7_", prefix)),
      !!paste0(prefix, "_7_mean") := rollapply(!!sym(prefix), 7, mean, na.rm = TRUE, fill = NA, align = 'right', partial = TRUE),
      !!paste0(prefix, "_7_sd") := roll_sd(!!sym(prefix), 7, min_obs = 1),
      !!paste0("monotonie_", prefix) := round(!!sym(paste0(prefix, "_7_mean")) / !!sym(paste0(prefix, "_7_sd")), digits = 1),
      !!paste0("monotonie_", prefix) := ifelse(!!sym(paste0("monotonie_", prefix)) >= 10, 0, !!sym(paste0("monotonie_", prefix)))
    )
}

# Apply the function for both load_rpe and load_rpe_velo
srss_wellness_training <-
  merge(srss_wellness,
        srss_training_day,
        by = c("date", "nom"),
        all = TRUE) %>%
  group_by(nom) %>%
  fill(c(courriel, hrv_android_minus_1d, ath_id, api_key),
       .direction = "up") %>%
  ungroup() %>%
  filter(n() > 1) %>%
  mutate(across(c(load_rpe, load_rpe_velo), ~ replace(., is.na(.), 0))) %>%
  group_by(nom) %>%
  calculate_metrics(., "load_rpe") %>%
  calculate_metrics(., "load_rpe_velo") %>%
  mutate(
    feeling_training_mean_velo_ravg7 = rollapply(
      feeling_training_mean_velo,
      7,
      mean,
      na.rm = TRUE,
      fill = NA,
      align = 'right',
      partial = TRUE
    ),
    feeling_training_mean_velo_ravg60_bike = rollapply(
      feeling_training_mean_velo,
      60,
      mean,
      na.rm = TRUE,
      fill = NA,
      align = 'right',
      partial = TRUE
    ),
    feeling_training_mean_velo_norm = 0.75 * (roll_sd(feeling_training_mean_velo, 60, min_obs = 1))
  ) |>
  ungroup()
```

```{r merge all in one df}
merged_df <- srss_wellness_training |> 
  # ensures merged data overlapping columns uniquely labeled, preventing duplication with suffixes argument
  merge(intervals_activities, by = c("date", "nom"), all = TRUE, suffixes = c(".srss", ".activities")) |> 
  merge(intervals_wellness, by = c("date", "nom"), all = TRUE, suffixes = c(".srss", ".wellness")) |> 
  select(-ends_with(".srss"), -ends_with(".activities"), -ends_with(".wellness"))

metriques_ext_int <- merged_df %>%
  select(date, nom, courriel, ath_id, api_key, icu_joules_bike, lutrimp_bike, load_rpe_velo) %>%
  replace_na(list(icu_joules_bike = 0, lutrimp_bike = 0, load_rpe_velo = 0)) %>%
  filter(icu_joules_bike != 0 & lutrimp_bike != 0 & load_rpe_velo != 0) %>%
  group_by(ath_id) %>% 
  mutate(
    # lutrimp
    aigue_7_lutrimp_g = EMA(lutrimp_bike, n = 1, ratio = 2 / (1 + 7)),
    chronique_42_lutrimp_g = EMA(lutrimp_bike, n = 1, ratio = 2 / (1 + 42)),
    ACWR_lutrimp_g = aigue_7_lutrimp_g / chronique_42_lutrimp_g,
    #  joules
    aigue_7_j_g = EMA(icu_joules_bike, n = 1, ratio = 2 / (1 + 7)),
    chronique_42_j_g = EMA(icu_joules_bike, n = 1, ratio = 2 / (1 + 42)),
    ACWR_j_g = aigue_7_j_g / chronique_42_j_g,
    # rpe
    aigue_7_rpe_g = EMA(load_rpe_velo, n = 1, ratio = 2 / (1 + 7)),
    chronique_42_rpe_g = EMA(load_rpe_velo, n = 1, ratio = 2 / (1 + 42)),
    ACWR_rpe_g = aigue_7_rpe_g / chronique_42_rpe_g,
    # roll avg pour mieux voir tendances
    ACWR_rpe_g_ravg = rollapply(
      ACWR_rpe_g,
      7,
      mean,
      na.rm = TRUE,
      fill = NA,
      align = 'right',
      partial = TRUE
    ),
    ACWR_lutrimp_g_ravg = rollapply(
      ACWR_lutrimp_g,
      7,
      mean,
      na.rm = TRUE,
      fill = NA,
      align = 'right',
      partial = TRUE
    ),
    ACWR_j_g_ravg = rollapply(
      ACWR_j_g,
      7,
      mean,
      na.rm = TRUE,
      fill = NA,
      align = 'right',
      partial = TRUE
    ),
    # SD de roll avg 
    ACWR_rpe_g_ravg_sd = roll_sd(ACWR_rpe_g_ravg, 7, min_obs = 1),
    ACWR_lutrimp_g_ravg_sd = roll_sd(ACWR_lutrimp_g_ravg, 7, min_obs = 1),
    ACWR_j_g_ravg_sd = roll_sd(ACWR_j_g_ravg, 7, min_obs = 1)
  )

database <- merged_df %>%
  merge(
    metriques_ext_int,
    by = c("date", "nom"),
    all = TRUE,
    # ensures merged data overlapping columns uniquely labeled, preventing duplication with suffixes argument
    suffixes = c("", "_metriques_ext_int")
  ) %>%
  select(-ends_with("_metriques_ext_int"))
```

```{r % responses form}
# Assuming your dataframe is named df
filtered_df <- database %>%
  group_by(nom) %>%
  # filter df to get the first day the form was filed
  filter(date >= date[which.min(is.na(overall_recovery))]) %>%
  ungroup()

# Assuming your dataset is named df
# First, calculate the earliest and latest response dates for each person (nom)
response_dates <- filtered_df |>
  group_by(nom) |>
  summarize(first_response_date = min(date),
            last_response_date = max(date))

# Create a sequence of dates from the earliest to the latest response date for each person
full_date_period <- response_dates |>
  mutate(date = map2(
    first_response_date,
    last_response_date,
    ~ seq.Date(from = .x, to = .y, by = "1 day")
  )) |>
  unnest(date)

# Merge the full date period with the original dataset to fill in missing dates
full_df <- full_date_period |>
  left_join(filtered_df, by = c("nom", "date"))

# Now, calculate the percentage of responses for each person
percentage_responses <- full_df %>%
  select(nom, date, overall_recovery, load_rpe_velo, icu_joules_bike, lutrimp_bike) |> 
  # vars 0 to NA
  mutate_if(is.numeric, list(~ ifelse(. == 0, NA, .))) |> 
  group_by(nom) %>%
  # summarize but not for date column
  summarize(across(-date, ~ sum(!is.na(.)) / length(.)),
            total_days = n_distinct(date)) %>%
  mutate(
    form_percent = round(overall_recovery * 100),
    icu_joules_bike_percent = round(icu_joules_bike / load_rpe_velo * 100),
    # correction si plus de jour avec pwr ou fc que rpe
    icu_joules_bike_percent = ifelse(icu_joules_bike_percent > 100, 100, icu_joules_bike_percent),
    lutrimp_bike_percent = round(lutrimp_bike / icu_joules_bike * 100),
    # correction si moins de jour avec pwr que fc
    lutrimp_bike_percent = ifelse(lutrimp_bike_percent > 100, 100, lutrimp_bike_percent)
  ) %>%
  ungroup() %>%
  select(nom,
         total_days,
         form_percent,
         icu_joules_bike_percent,
         lutrimp_bike_percent)
```

```{r csv}
write.csv(database, file = "~/Desktop/Ltips/etude_ai/database.csv", row.names = FALSE)
write.csv(intervals_power, file = "~/Desktop/Ltips/etude_ai/mmp.csv", row.names = FALSE)
```

